package vista;

import adaptador.Adaptador;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Toni Garcia
 */
public class AfegirComanda extends javax.swing.JFrame {
    GestioComandes parent;
    Adaptador ad;  
    boolean allFilled;
    /**
     * Creates new form AfegirComanda
     */
    public AfegirComanda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtQtty = new javax.swing.JTextField();
        checkIsUrgent = new javax.swing.JCheckBox();
        lblClient = new javax.swing.JLabel();
        lblArticle = new javax.swing.JLabel();
        lblQty = new javax.swing.JLabel();
        btnAfegir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cbClient = new javax.swing.JComboBox<>();
        cbArticle = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Afegir Comanda Nova");

        txtQtty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQttyKeyReleased(evt);
            }
        });

        checkIsUrgent.setText("Comanda urgent");

        lblClient.setText("Client");

        lblArticle.setText("Article");

        lblQty.setText("Quantitat");

        btnAfegir.setText("Afegir");
        btnAfegir.setEnabled(false);
        btnAfegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        cbClient.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbClientFocusGained(evt);
            }
        });
        cbClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbClientMouseReleased(evt);
            }
        });

        cbArticle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbArticleFocusGained(evt);
            }
        });
        cbArticle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbArticleMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtQtty, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(checkIsUrgent)
                        .addGap(141, 141, 141))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClient)
                            .addComponent(cbClient, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblArticle)
                            .addComponent(cbArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQty))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAfegir)
                        .addGap(63, 63, 63))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(lblClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblArticle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbArticle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lblQty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkIsUrgent)
                    .addComponent(txtQtty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAfegir))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        parent.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAfegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirActionPerformed
        // TODO add your handling code here:
        try{ 
            ad.afegirComanda(cbArticle.getSelectedIndex(), cbClient.getSelectedIndex(), Integer.parseInt(txtQtty.getText()), checkIsUrgent.isSelected());
            this.setVisible(false);
            parent.setVisible(true);
            parent.llistarComandes();
        }
           catch (Exception e){
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnAfegirActionPerformed

    private void cbClientMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbClientMouseReleased
        // TODO add your handling code here:
        allFilled = cbClient.getSelectedIndex() != -1 && cbArticle.getSelectedIndex() != -1
                && !txtQtty.getText().equals("");
        btnAfegir.setEnabled(allFilled);
    }//GEN-LAST:event_cbClientMouseReleased

    private void cbArticleMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbArticleMouseReleased
        // TODO add your handling code here:
        allFilled = cbClient.getSelectedIndex() != -1 && cbArticle.getSelectedIndex() != -1
                && !txtQtty.getText().equals("");
        btnAfegir.setEnabled(allFilled);
    }//GEN-LAST:event_cbArticleMouseReleased

    private void txtQttyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQttyKeyReleased
        // TODO add your handling code here:
        allFilled = cbClient.getSelectedIndex() != -1 && cbArticle.getSelectedIndex() != -1
                && !txtQtty.getText().equals("");
        btnAfegir.setEnabled(allFilled);
    }//GEN-LAST:event_txtQttyKeyReleased

    private void cbArticleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbArticleFocusGained
        // TODO add your handling code here:
        // Relleno el cbArticles con los valores de la lista de Articles.
        cbArticle.removeAllItems();
        try{
            for (String Val : ad.printLlistaArticles()){
                cbArticle.addItem(Val);
            }
        }catch (Exception r){
        }        
    }//GEN-LAST:event_cbArticleFocusGained

    private void cbClientFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbClientFocusGained
        // TODO add your handling code here:
        //Relleno el cbClients con los valores de la lista Clients.
        cbClient.removeAllItems();
        try{
            for (String Val : ad.printLlistaClients()){
                cbClient.addItem(Val);
            }
        }catch (Exception r){
            
        }
    }//GEN-LAST:event_cbClientFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AfegirComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AfegirComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AfegirComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AfegirComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AfegirComanda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfegir;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbArticle;
    private javax.swing.JComboBox<String> cbClient;
    private javax.swing.JCheckBox checkIsUrgent;
    private javax.swing.JLabel lblArticle;
    private javax.swing.JLabel lblClient;
    private javax.swing.JLabel lblQty;
    private javax.swing.JTextField txtQtty;
    // End of variables declaration//GEN-END:variables

    void Show(GestioComandes aThis) {
        parent=aThis;
        ad = parent.ad;
        this.setVisible(true);
        aThis.setVisible(false);
    }
}