package vista;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import adaptador.Adaptador;
import javax.swing.JOptionPane;

/**
 *
 * @author garci
 */
public class AppMercatUB extends javax.swing.JFrame {

    public Adaptador ad = new Adaptador();  
    AfegirArticle afArticle;
    AfegirClient afClient;
    GestioComandes gesCom;
    
    /**
     * Creates new form AppMercatUB
     */
    public AppMercatUB() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        btnAfegirClient = new javax.swing.JButton();
        btnAfegirArticle = new javax.swing.JButton();
        btnGestioComandes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listLlistar = new javax.swing.JList<>();
        btnLlistarClients = new javax.swing.JButton();
        btnLlistarArticles = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArxiu = new javax.swing.JMenu();
        MenuItemGuardar = new javax.swing.JMenuItem();
        MenuItemCarregar = new javax.swing.JMenuItem();
        MenuAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("App Mercat UB");

        btnAfegirClient.setText("Afegir Client");
        btnAfegirClient.setName("btnAfegirClient"); // NOI18N
        btnAfegirClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirClientActionPerformed(evt);
            }
        });

        btnAfegirArticle.setText("Afegir Article");
        btnAfegirArticle.setToolTipText("");
        btnAfegirArticle.setName("btnAfegirArticle"); // NOI18N
        btnAfegirArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirArticleActionPerformed(evt);
            }
        });

        btnGestioComandes.setText("Gestió comandes");
        btnGestioComandes.setName("btn_gestioComandes"); // NOI18N
        btnGestioComandes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestioComandesActionPerformed(evt);
            }
        });

        listLlistar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listLlistar.setName("listLlistar"); // NOI18N
        jScrollPane1.setViewportView(listLlistar);

        btnLlistarClients.setText("Llistar Clients");
        btnLlistarClients.setName("btnLlistarClients"); // NOI18N
        btnLlistarClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlistarClientsActionPerformed(evt);
            }
        });

        btnLlistarArticles.setText("Llistar Articles");
        btnLlistarArticles.setName("btnLlistarArticles"); // NOI18N
        btnLlistarArticles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlistarArticlesActionPerformed(evt);
            }
        });

        menuArxiu.setText("Arxiu");

        MenuItemGuardar.setText("Guardar dades");
        MenuItemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemGuardarActionPerformed(evt);
            }
        });
        menuArxiu.add(MenuItemGuardar);

        MenuItemCarregar.setText("Carregar dades");
        MenuItemCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCarregarActionPerformed(evt);
            }
        });
        menuArxiu.add(MenuItemCarregar);

        jMenuBar1.add(menuArxiu);

        MenuAjuda.setText("Ajuda");
        jMenuBar1.add(MenuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGestioComandes, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAfegirClient, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAfegirArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLlistarArticles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLlistarClients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAfegirClient, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLlistarClients, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLlistarArticles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAfegirArticle))
                        .addGap(151, 151, 151)
                        .addComponent(btnGestioComandes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLlistarClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlistarClientsActionPerformed
        // TODO add your handling code here:
        DefaultListModel<String> llista = new DefaultListModel<>();
        try{
            for (String Val : ad.printLlistaClients()){
                llista.addElement(Val);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);            
        }
        listLlistar.setModel(llista);
    }//GEN-LAST:event_btnLlistarClientsActionPerformed

    private void btnLlistarArticlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlistarArticlesActionPerformed
        // TODO add your handling code here:
        DefaultListModel<String> llista = new DefaultListModel<>();
        try{
            for (String Val : ad.printLlistaArticles()){
                llista.addElement(Val);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);            
        }
        listLlistar.setModel(llista);
    }//GEN-LAST:event_btnLlistarArticlesActionPerformed

    private void btnAfegirClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirClientActionPerformed
        // TODO add your handling code here:
        if (afClient == null){
            afClient = new AfegirClient();
        }
        afClient.Show(this);
    }//GEN-LAST:event_btnAfegirClientActionPerformed

    private void btnAfegirArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirArticleActionPerformed
        // TODO add your handling code here:
        if (afArticle == null){
            afArticle = new AfegirArticle();
        }
        afArticle.Show(this);
    }//GEN-LAST:event_btnAfegirArticleActionPerformed

    private void btnGestioComandesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestioComandesActionPerformed
        // TODO add your handling code here:
        if (gesCom == null){
            gesCom = new GestioComandes();
        }
        gesCom.Show(this);
        gesCom.llistarComandes();
    }//GEN-LAST:event_btnGestioComandesActionPerformed

    private void MenuItemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemGuardarActionPerformed
        // TODO add your handling code here:
        try{
            File fitxer;
            JFileChooser seleccio = new JFileChooser();
            int resultat = seleccio.showOpenDialog(this);
            if (resultat == JFileChooser.APPROVE_OPTION) {
                fitxer=seleccio.getSelectedFile();
                ad.guardaDades(fitxer.toString());
            }
        }catch (Exception e){ 
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_MenuItemGuardarActionPerformed

    private void MenuItemCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCarregarActionPerformed
        // TODO add your handling code here:
        try{
            File fitxer;
            JFileChooser seleccio = new JFileChooser();
            int resultat = seleccio.showOpenDialog(this);
            if (resultat == JFileChooser.APPROVE_OPTION) {
                fitxer=seleccio.getSelectedFile();
                ad.carregaDades(fitxer.toString());
            }
        }catch (Exception e){ 
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_MenuItemCarregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppMercatUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppMercatUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppMercatUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppMercatUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppMercatUB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAjuda;
    private javax.swing.JMenuItem MenuItemCarregar;
    private javax.swing.JMenuItem MenuItemGuardar;
    private javax.swing.JButton btnAfegirArticle;
    private javax.swing.JButton btnAfegirClient;
    private javax.swing.JButton btnGestioComandes;
    private javax.swing.JButton btnLlistarArticles;
    private javax.swing.JButton btnLlistarClients;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listLlistar;
    private javax.swing.JMenu menuArxiu;
    // End of variables declaration//GEN-END:variables
}
