package p3gui.vista;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import prog2.adaptador.Adaptador;

/**
 *
 * @author garci
 */
public class AppMercatUB extends javax.swing.JFrame {

        Adaptador ad = new Adaptador();
    /**
     * Creates new form AppMercatUB
     */
    public AppMercatUB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAfegirClient = new javax.swing.JButton();
        btnAfegirArticle = new javax.swing.JButton();
        btnGestioComandes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listLlistar = new javax.swing.JList<>();
        btnLlistarClients = new javax.swing.JButton();
        btnLlistarArticles = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAfegirClient.setText("Afegir Client");
        btnAfegirClient.setName("btnAfegirClient"); // NOI18N
        btnAfegirClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirClientActionPerformed(evt);
            }
        });

        btnAfegirArticle.setText("Afegir Article");
        btnAfegirArticle.setToolTipText("");
        btnAfegirArticle.setName("btnAfegirArticle"); // NOI18N

        btnGestioComandes.setText("Gestió comandes");
        btnGestioComandes.setName("btn_gestioComandes"); // NOI18N

        listLlistar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listLlistar.setName("listLlistar"); // NOI18N
        jScrollPane1.setViewportView(listLlistar);

        btnLlistarClients.setText("Llistar Clients");
        btnLlistarClients.setName("btnLlistarClients"); // NOI18N
        btnLlistarClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlistarClientsActionPerformed(evt);
            }
        });

        btnLlistarArticles.setText("Llistar Articles");
        btnLlistarArticles.setName("btnLlistarArticles"); // NOI18N
        btnLlistarArticles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlistarArticlesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGestioComandes, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAfegirArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAfegirClient, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnLlistarClients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLlistarArticles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAfegirClient, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                            .addComponent(btnLlistarClients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLlistarArticles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAfegirArticle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGestioComandes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLlistarClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlistarClientsActionPerformed
        // TODO add your handling code here:
        DefaultListModel<String> llista = new DefaultListModel<>();
        try{
            for (String Val : ad.printLlistaClients()){
                llista.addElement(Val);
            }
        }catch (Exception e){
            
        }
        listLlistar.setModel(llista);
    }//GEN-LAST:event_btnLlistarClientsActionPerformed

    private void btnLlistarArticlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlistarArticlesActionPerformed
        // TODO add your handling code here:
        DefaultListModel<String> llista = new DefaultListModel<>();
        try{
            for (String Val : ad.printLlistaArticles()){
                llista.addElement(Val);
            }
        }catch (Exception e){
            
        }
        listLlistar.setModel(llista);
    }//GEN-LAST:event_btnLlistarArticlesActionPerformed

    private void btnAfegirClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirClientActionPerformed
        // TODO add your handling code here:
        AfegirClient.
    }//GEN-LAST:event_btnAfegirClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppMercatUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppMercatUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppMercatUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppMercatUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppMercatUB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfegirArticle;
    private javax.swing.JButton btnAfegirClient;
    private javax.swing.JButton btnGestioComandes;
    private javax.swing.JButton btnLlistarArticles;
    private javax.swing.JButton btnLlistarClients;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listLlistar;
    // End of variables declaration//GEN-END:variables
}
